name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v5
      - name: Get tag version
        id: get_tag_version
        run: echo TAG_VERSION=$(cat "version.txt" | tr -d '\n') >> $GITHUB_OUTPUT
      - name: Read Tag version
        run: |
          echo $TAG_VERSION
        env: 
          TAG_VERSION: ${{ steps.get_tag_version.outputs.TAG_VERSION }}
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: Check formatting
        run: deno fmt --check
      - name: Test with coverage output
        run: deno test --doc --coverage=coverage
      - name: Lint source
        run: deno lint
      - name: Test with coverage output
        run: deno test --doc --coverage=coverage
      - name: Convert coverage details to a report file
        run: deno coverage ./coverage --lcov > coverage.lcov
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          use_oidc: true
          files: ./coverage.lcov
          slug: LeviSchuck/tiny-cbor-schema
          fail_ci_if_error: true
